name: Build and Push Docker Image

# Trigger the workflow on push to main branch or any other branches you specify
on:
  push:
    branches:
      - main
      - master
      - 'release/**'  # optional, for release branches
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Display Branch Name
        run: |
          echo "To get source branch Name : ${{github.ref_name}}"
          echo "For Target branch Name : ${{github.event.pull_request.base.ref}}"
          echo "${{ github.head_ref || github.ref_name }}"
          echo "base ref : ${{ github.base_ref }}"

      - name: Extract and sanitize branch name
        id: extract_branch
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^a-zA-Z0-9_.-]/-/g')
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

#      # Step 4: Extract the version from package.json (optional)
#      - name: Extract version from package.json
#        id: vars
#        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV_VERSION

      # Step 5: Build and push the Docker image
      - name: Build and Push Docker image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/zenith-ui:${{ github.head_ref || github.ref_name }}

      # Step 5: Build and push the Docker image :latest
      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/zenith-ui:latest
